image: Ubuntu2004

branches:
  only:
    - godMode

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc clang-format cppcheck valgrind make lcov check

build: off

build_script:
  - make -C src/ style_check
  - make -C src/brick_game test
  - make -C src/brick_game valgrind_test
  - make -C src/brick_game cpp_check
  - make -C src/brick_game gcov_report