image: Ubuntu2204

branches:
  only:
    - godMode

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc cppcheck valgrind make lcov check
  - wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s 18
  - sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-18 100

build: off

build_script:
  - make -C src/ style_check
  - make -C src/brick_game test
  - make -C src/brick_game valgrind_test
  - make -C src/brick_game cpp_check